" Environment
set backupdir=$XDG_CACHE_HOME/vim/backup,~/,/tmp
set directory=$XDG_CACHE_HOME/vim/swap,~/,/tmp
set undodir=$XDG_CACHE_HOME/vim/undo,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
